DROP DATABASE IF EXISTS mercado_db;
DROP USER IF EXISTS `mercado_db_user`@`%`;
CREATE DATABASE IF NOT EXISTS mercado_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `mercado_db_user`@`%` IDENTIFIED WITH mysql_native_password BY 'mercado123';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `mercado_db`.* TO `mercado_db_user`;
